### Makefile --- 

## Author: shell@deb64.lan
## Version: $Id: Makefile,v 0.0 2012/11/26 13:41:42 shell Exp $
## Keywords: 
## X-URL: 
TARGET=server client
CC=gcc

all: build

build: $(TARGET)

server: server.o

### Makefile ends here
